spring:
  application:
    name: vue-admin-template
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: development
    password: crushonZYY1314!
    url: jdbc:mysql://rm-bp18ho13039kl0if1bo.mysql.rds.aliyuncs.com:3306/development?useSSL=true&serverTimezone=Asia/Shanghai

  mail:
    host: smtp.163.com
    username: luckierlove@163.com
    password: BXLZKVXCPCAHCXUA
    port: 465
    protocol: smtps
  data:
    redis:
      host: localhost
      database: 0
      port: 6379
  web:
    verify:
      mail-limit: 60
server:
  servlet:
    context-path: /api